version: '3.8'
services:
  gateway:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./shareit-service
    container_name: shareit-service
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=Admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
  db:
    image: postgres:14.5-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=123